### ISSUE TITLE
404 Error loading bound value after successfully loading a different value

### ISSUE THREAD

**Issue by scothis** [servicebinding/conformance#64]
<img width="1642" alt="Screenshot 2023-08-08 at 2 06 31 PM" src="https://github.com/servicebinding/conformance/assets/302992/893ed48a-7832-4840-9189-80d7bc80c5e6">

acceptance-test-results: https://github.com/servicebinding/conformance/files/12294605/acceptance-test-results.zip

source https://github.com/servicebinding/runtime/actions/runs/5798222003/job/15715710115?pr=311

**Comment by sadlerap** [comment]
Thanks for the tracking issue, I'll take a look.  I know I've run into this before, but reproducing it locally hasn't been easy for me to do.

I suspect it's an issue with the test framework, since poking the relevant endpoints with `curl` has usually worked in the past.  However, I'm not 100% convinced, so I'll do a bit more of a dive.

**Comment by scothis** [comment]
I assume the request to fetch the `username` field worked before the `password` fields 404ed. The 404 makes me thing the issue may be in the test app.

**Comment by scothis** [comment]
Hit a new failure in almost the same spot 
<img width="2158" alt="Screenshot 2023-08-16 at 11 29 34 AM" src="https://github.com/servicebinding/conformance/assets/302992/1a3d992f-0115-48ce-841f-7b76a7dd3536">
